- name: Get information about VPCs
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Fetch VPC information
      amazon.aws.ec2_vpc_net_info:
        region: "{{ aws_default_region }}"
      register: vpcs_info

    - name: Print VPC information
      debug:
        var: vpcs_info
